# From: https://github.com/shuhaoliu/docker-clion-dev/blob/master/docker-compose.yml

version: '3'

services:
  gdbserver:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: kmymoney_dev
    security_opt:
      - seccomp:unconfined
    container_name: debug
    volumes:
      - ~/KMyMoney:/config
      - ~/.aqbanking:/root/.aqbanking
      - ~/.config/kmymoney:/root/.config/kmymoney
      - ~/.gdbinit:/root/.gdbinit
      - ~/.gdb:/root/.gdb
      - build:/build
    ports:
      - "7776:22"
    environment:
      - DISPLAY=host.docker.internal:0
    hostname: debug

volumes:
  build: